### ISSUE TITLE
Access to ros2/ci-builders Team

### ISSUE THREAD

**Issue by dkroenke** [ros2-gbp/iceoryx-release#1]
Hi,
a question maybe to @nuclearsandwich: Can one (or two for vacations) maybe get access to `ros2/ci-builders` team and therefore the ability to trigger jenkins jobs on https://ci.ros2.org ?

The main reason is to test the iceoryx releases before blooming them into ROS to make sure that nothing breaks.
Like cyclonedds, the iceoryx project is hosted under the eclipse umbrella in Github and we don't have admin rights on that repository.
We have of course also a colcon build in our CI and try to cover as much compilers as possible. It is not planned to consume this CI often, it is more intented as a last check before running bloom and we don't want to bother you or Chris all the time with build requests.

Let me know what you think if that is possible.

**Comment by nuclearsandwich** [comment]
@clalancette I think it's fine to add a couple more rmw-layer folks but I'll defer to you.

**Comment by clalancette** [comment]
> @clalancette I think it's fine to add a couple more rmw-layer folks but I'll defer to you.

It's OK with me.  @dkroenke what GitHub users did you have in mind.

> The main reason is to test the iceoryx releases before blooming them into ROS to make sure that nothing breaks.

Keep in mind that the jobs that run on https://ci.ros2.org are related to, but not the same as, what gets bloomed onto the https://build.ros2.org buildfarm.  A successful run on https://ci.ros2.org won't guarantee that there are no bloom issues; in particular, if you are missing declared dependencies, a run on https://ci.ros2.org probably won't tell you that.

Nevertheless, it is a good idea to always run a build on https://ci.ros2.org before releasing, since that will point out most code-related issues on all platforms.

**Comment by dkroenke** [comment]
> It's OK with me. @dkroenke what GitHub users did you have in mind.

@clalancette 
I would nominate @mossmaurice @elBoberido taken from the [iceoryx_team](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/iceoryx.tf)
Let me know if there are any hints/restrictions on the CI beside the mentioned one on the [CI Builders Readme](https://github.com/ros2/ci/blob/master/CI_BUILDERS.md).

**Comment by dkroenke** [comment]
@clalancette Just a friendly ping from me to remember that my two mates and me would like to join the ci-builders team.
At least I cannot see the build button in the `ci_launcher` job.

**Comment by dkroenke** [comment]
@clalancette or @nuclearsandwich Do you need other information from us? Let me know if I can help.

**Comment by nuclearsandwich** [comment]
> @clalancette or @nuclearsandwich Do you need other information from us? Let me know if I can help

Nope we were actually going through our internal docs trying to find the most up-to-date onboarding info so there was some back-and-forth for that.

I've sent the invitations to join the ros2/ci-builders team. Be sure to accept that invitation before attempting to authenticate on ci.ros2.org as Jenkins will cache your organization and team memberships for up to 24 hours preventing your elevated permissions from applying right away.

> [](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/iceoryx.tf?rgh-link-date=2022-02-18T08%3A05%3A41Z)
> Let me know if there are any hints/restrictions on the CI beside the mentioned one on the [CI Builders Readme](https://github.com/ros2/ci/blob/master/CI_BUILDERS.md?rgh-link-date=2022-02-18T08%3A05%3A41Z).

That document has the highlights and thanks to clalancette's work there is much more description on the . There is some additional context and workflow documentation in the [ROS 2 contributing developer guide](https://docs.ros.org/en/ros2_documentation/galactic/Contributing/Developer-Guide.html#developer-workflow).

If you have any questions feel free to open issues on https://github.com/ros2/ci

**Comment by dkroenke** [comment]
@nuclearsandwich 
Thanks for the invite! I can confirm that I'm now able to build on the ROS 2 CI.
I will close this issue now here.
